global:
  scrape_interval: 15s
  evaluation_interval: 1m
  scrape_timeout: 10s

  external_labels:
    monitor: 'docker-monitor'

rule_files:
  - "rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'department name'
    file_sd_configs:
      - files:
          - 'targets/department name.yml'
    relabel_configs:
      - source_labels: [__address__]
        regex: '([^:]+):.*'
        target_label: instance_ip
        replacement: '${1}'
